### ISSUE TITLE
Add ability to add default reviewers based on a file from repo

### ISSUE THREAD

**Issue by amnk** [blancmanges/gatekeeper#9]
I guess we can adopt [linux community approach](https://www.kernel.org/doc/linux/MAINTAINERS)

**Comment by kgadek** [comment]
There are two aspects here: the format and the way to obtain this description.

## Format

Linux approach is really comprehensive, but requires custom parsers and is arguably unreadable by mortals 😉 It is not directly applicable to BitBucket, as the focus is on mailing lists. Thus I would propose a format based on it.

- YAML format, so no custom parsers would be necessary
- a combo of M+R fields to specify BitBucket username of person who is able to review a chunk of code,
- an F field(s) for specifying what is covered by above.

I'll provide file format spec that I have in mind in other PR.

## Obtaining the description

I think I like approach A with partial-clone better.

### Approach A

The thing that bothers me the most in Linux approach is that it will require Gatekeeper to use Git to grab the MAINTAINERS file. We could grab one file from repo [[SO: "How to checkout only one file from git repository"](https://stackoverflow.com/q/2466735/547223)] or keep a local (bare) mirror to prevent full clone each time. The former preserves "stateless-ness", but incorporates Git & requires additional credentials in place (`id_rsa` probably). The latter is stateful (maintains disk cache) and has all downsides of former approach, but will allow more flexibility (flexibility could mean e.g. scanning whole repo).

### Approach B

The alternative is to provide this information as runtime variable. This is much simpler (no Git, no cloning, less network traffic), but will require to re-deploy gatekeeper on each change. Also, the responsibility to keep description up-to-date is moved from actual team to person/team deploying gatekeeper.

**Comment by kgadek** [comment]
# Proposal for a format.

Syntactically this shall be self explanatory (otherwise it's a bug).

```yaml
gatekeeper_format: 1

groups:

  - group_a:
      - user_a  # note: user_a & user_b are assigned to multiple groups
      - user_b
      - user_c

  - group_b:
      - user_d
      - user_b
      - user_a

pull_requests:

  - paths:
      - .

    pr_reviewers:
      - "@@group_a"
      - user_h
      - user_i

    designated_reviewers:
      assign:
          from:
            - "@@group_a"
          count: 2
      require: 2
    
    ci: true

    super_votes:  # +2 overrides requirements above
      - user_a
      - user_c

  - paths:
      - directory/foobar
      - directory/foobaz

    pr_reviewers:
      - "@@group_b"

    designated_reviewers:
      assign:
        from:
          - "@@group_b"
          - user_j
        count: 1
      require: 1
```

### Discussion

Below, I'm using "path group" to describe each entry under `pull_requests` top-level group.

- `group` section & usage seem useful especially in monorepos. Also they seem to improve readability a bit. To reference, I've used `@@` prefix to disambiguate things as much as possible: without prefix there could be conflict, while single `@` is usually used for users. The unfortunate thing is that `@` is a reserved character in [YAML 1.2 spec](http://yaml.org/spec/1.2/spec.html#id2772075), thus `" "` is required. Surely, we could implement this later
- globs in paths are probably a feature that could be added much later. It seems that in most cases, simple dir-based matching should be enough
- `pr_reviewers` and `designated_reviewers` mean something slightly different: the former is solely for attaching people to PR (thing "CC" in mails), the latter is a decisive group that shall take responsibility and do the actual review
- paths could overlap. Then, the system should use the conjunction of requirements (logical AND). Therefore, the "path group" that covers `.` path can be seen as "default" rule set.
- there is no "super-super-vote" by design (at least for now). This means that if PR covers multiple "path groups", and one "path group" allows `+2`, then such vote isn't decisive for whole PR

Initially, I was thinking about splitting requirements from "definitions", for example:

```yaml
  - paths:
      - directory/foobar
      - directory/foobaz

    pr_reviewers:
      - "@@group_b"

    on_create:
      - assign_designated_reviewers:
          from: # …snip

    requirements:
      - ci: true
      - designated_reviewers:
          - any: 2
            vote: "+1"
```

However, this would induce additional semantics checks. For example, it's an error to specify `designated_reviewers` in `requirements` without specifying `assign_designated_reviewers` in `on_create`. The current approach follows a "correctness by construction" mantra: if YAML parses, then it's mostly correct.

There is a possibly surprising effect of all of above. If `user_a` is listed as designated reviewer in multiple "path grups", then:

- `user_a` maybe wouldn't be designated reviewer for this PR,
- `user_a` maybe would be designated reviewer for one path group for this PR,
- `user_a` maybe would be designated reviewer for multiple path groups for this PR.

The last possibility means

- `user_a` votes cover all of paths
- the number of designated reviewers may vary, depending on the random assignments

I was thinking how to select `designated_reviewers`. If that would be done in truly random fashion, then gatekeeper would need to store this (probably in comments). However, there is simpler solution: seed the RNG using PRs original state. Then, the pseudo-random pick could be regenerated at any later time. This would consume part of BitBucket API that can't change (if there is any such). On the other side, gatekeeper writing comment describing who should vote should land anyway.
